//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeriodicTableOfElements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeriodicTableOfElements.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;root&gt;
        ///  &lt;row order=&quot;1&quot;&gt;
        ///    &lt;elem name=&quot;H&quot; text=&quot;1\nH&quot; color=&quot;#FFEA84&quot;/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;elem name=&quot;He&quot; text=&quot;2\nHe&quot; color=&quot;#7CFFFF&quot;/&gt;
        ///  &lt;/row&gt;
        ///  &lt;row order=&quot;2&quot;&gt;
        ///    &lt;elem name=&quot;Li&quot; text=&quot;3\nLi&quot; color=&quot;#FF4F4F&quot;/&gt;
        ///    &lt;elem name=&quot;Be&quot; text=&quot;4\nBe&quot; color=&quot;#FFD177&quot;/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt;
        ///    &lt;bl/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
    }
}
